Repository atlasconsulting/nuxt-bedita, pull requests merged in 2024-03, with the labels that each got.

#26 fix: auto import SSR utility functions
  src/module.ts
Labels: release:patch

#27 feat: introduce routes guard
  README.md
  docs/content/1.getting-started/2.configuration.md
  docs/content/2.features/2.middleware.md
  docs/content/2.features/3.composables.md
  src/module.ts
  src/runtime/middleware/auth.ts
Labels: enhancement, release:minor

#28 ci: add dependabot.yml configuration
  .github/dependabot.yml
Labels: CI

#29 feat: add "redirect" query string in sign-in redirect
  src/runtime/middleware/auth.ts
Labels: enhancement, release:minor
